gfp/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^$', 'players.views.index', name='players-index'),
    url(r'^gfp-system/', include('scoreboard.urls', namespace='scoreboard')),
    url(r'^player/', include('players.urls', namespace='players')),
    url(r'^games/', include('games.urls', namespace='games')),
    url(r'^grappelli/', include('grappelli.urls')),
    url(r'^admin/', admin.site.urls)
]

players/urls.py
from django.conf.urls import url
from django.contrib.auth import views as auth_views


from . import views

urlpatterns = [
    url(r'^login$', views.login_view, name="players-login"),
    url(r'^logout$', auth_views.logout, name="players-logout")
]

scoreboard/urls.py
from django.conf.urls import url
from django.contrib import admin

from . import views

urlpatterns = [
    url(r'^scoreboard$', views.scoreboard_view, name='scoreboard'),
    url(r'^guessing/(?P<id>[0-9]+)$', views.guess_view, name='guessing-form'),
    url(r'^redeem$', views.redemption_view, name='redemption')
]

players/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class Player(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)

    def __str__(self):
        if not self.user.first_name and not self.user.last_name:
            return '%s' % (self.user.username)
        return '%s %s' % (self.user.first_name, self.user.last_name)

players/views.py
from django.contrib import messages
from django.contrib.auth import login, logout
from django.db.models import Q, F, Sum
from django.shortcuts import render, redirect
from django.shortcuts import HttpResponseRedirect
from django.contrib.auth.forms import AuthenticationForm

from games.models import Guess
from players.models import Player
from scoreboard.forms import PointCodeForm, GuessingForm
from scoreboard.models import Game, GameSession


def index(request):
    if not request.user.is_authenticated():
        return redirect('players:players-login')
    elif not hasattr(request.user, 'player'):
        if request.user.is_staff:
            return redirect('admin:index')
        else:
            logout(request)
            messages.error(request, 'You are not a participant for this year\'s party.')
            return redirect('players:players-login')
    else:
        player = Player.objects.get(user=request.user)
        scores = player.score_set.all().filter(Q(game_session__game__display_leaderboard=True) |
                                               Q(game_session__isnull=True))\
                                       .values('game_session__game')\
                                       .annotate(total_score=Sum(F('score')), name=F('game_session__game__name'))

        total_score = sum(score['total_score'] for score in scores)

        active_guessing_games = GameSession.objects.filter(game__game_type=Game.GUESSING, is_active=True)\
                                                   .values('id', 'game__name')

        def get_forms(guess_game):
            try:
                guess_object = Guess.objects.get(player=request.user.player, game_session__id=guess_game['id'])
                guess_game['form'] = GuessingForm(instance=guess_object)
            except Guess.DoesNotExist:
                guess_game['form'] = GuessingForm()

            return guess_game

        active_guessing_games = map(get_forms, active_guessing_games)

        pointcode_form = PointCodeForm()

        return render(request, 'players/index.html', {'player': player, 'scores': scores, 'total': total_score,
                                                      'guessing_games': active_guessing_games,
                                                      'pointcode_form': pointcode_form})

def login_view(request):
    form = AuthenticationForm()

    if request.user.is_authenticated():
        return redirect('players-index')

    if request.POST:
        form = AuthenticationForm(request, request.POST)

        if form.is_valid():
            login(request, form.get_user())
            return redirect('players-index')

    return render(request, 'players/login.html', {'form': form})

players/templates/players/index.html
{% extends "index.html" %}
{% load addcss %}

{% block body %}
<div class="well well-sm">
  <h3 class="text-center" style="margin: 10px 0px">Overall Score: {{ total }}</h3>
</div>

<div class="panel panel-default">
    <div class="panel-heading text-center">
        <b>Enter VIP Codes</b>
    </div>
    <div class="panel-body">
        <form method="POST" action="{%url 'scoreboard:redemption' %}">
            {% csrf_token %}
            <input type="hidden" name="next" value="/" />
            <div class="form-group">
                {{ pointcode_form.code | addcss:"form-control input-lg"}}
            </div>
            <button type="submit" class="btn btn-default btn-block">Submit</button>
        </form>
    </div>
</div>

<div class="panel panel-default">
    <div class="panel-heading text-center">
        <b>Game Scores</b>
    </div>
    <div class="panel-body">
        <table class="table table-bordered table-striped">
            <thead>
                <th>GAME</th>
                <th>SCORE</th>
            </thead>
            {% for score in scores %}
                {% if score.name %}
                    <tr>
                        <td>{{ score.name }}</td>
                        <td>{{ score.total_score }} </td>
                    </tr>
                {% endif %}
            {% endfor %}
	    </table>
    </div>
</div>

<div class="panel panel-default">
    <div class="panel-heading text-center">
        <b>Guessing Games</b>
    </div>
    <div class="panel-body">
        {% for gamesession in guessing_games %}
            <div class="row">
                <div class="col-md-12">
                    <h4 class="text-center">{{ gamesession.game__name }}</h4>
                    <form method="POST" action="{% url 'scoreboard:guessing-form' id=gamesession.id %}">
                        {% csrf_token %}
                        <input type="hidden" name="next" value="/" />
                        <div class="form-group">
                            {{ gamesession.form.guess | addcss:"form-control input-lg"}}
                        </div>
                        <button type="submit" class="btn btn-default btn-block">Submit</button>
                    </form>
                </div>
            </div>
            {% if not forloop.last %}
            <hr/>
            {% endif %}
        {% endfor %}
    </div>
</div>
{% endblock %}

players/templates/players/login.html
{% extends "index.html" %}
{% load addcss %}

{% block body %}
<div class="well">
  <h2>Login</h2>
  <form method="POST" action="">
    {% csrf_token %}
    {% for field in form %}
      <div class="form-group">
        {{ field.label_tag }} {{ field | addcss:"form-control input-lg"}}
      </div>
    {% endfor %}
    <button type="submit" class="btn btn-default">Login</button>
  </form>
</div>
{% endblock %}