gfp/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^$', 'players.views.index', name='players-index'),
    url(r'^gfp-system/', include('scoreboard.urls', namespace='scoreboard')),
    url(r'^player/', include('players.urls', namespace='players')),
    url(r'^games/', include('games.urls', namespace='games')),
    url(r'^grappelli/', include('grappelli.urls')),
    url(r'^admin/', admin.site.urls)
]

scoreboard/urls.py
from django.conf.urls import url
from django.contrib import admin

from . import views

urlpatterns = [
    url(r'^scoreboard$', views.scoreboard_view, name='scoreboard'),
    url(r'^guessing/(?P<id>[0-9]+)$', views.guess_view, name='guessing-form'),
    url(r'^redeem$', views.redemption_view, name='redemption')
]

scoreboard/models.py
from django.db import models
from django.db.models import Q
from django.conf import settings
from django.core.exceptions import MultipleObjectsReturned

import datetime


class Game(models.Model):
    """
    Model to represent a Game
    """
    NORMAL = 'NM'
    GUESSING = 'GS'
    JUDGE = 'JD'
    LUCKY_DRAW = 'LD'
    GAME_TYPE_CHOICES = (
        (NORMAL, 'Normal'),
        (GUESSING, 'Guessing'),
        (JUDGE, 'Judge'),
        (LUCKY_DRAW, 'Lucky Draw')
    )
    game_type = models.CharField(
        max_length=2,
        choices=GAME_TYPE_CHOICES,
        default=NORMAL
    )
    name = models.CharField(max_length=255)

    base_score = models.IntegerField(default=0)
    changeable_score = models.BooleanField(default=False)

    is_active = models.BooleanField()
    display_leaderboard = models.BooleanField(default=True)

    def __str__(self):
        return '%s' % (self.name)


class GameSession(models.Model):
    """
    Represents a game session for a Game
    """
    game_master = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    game = models.ForeignKey('Game', on_delete=models.CASCADE)
    guess_value = models.PositiveIntegerField(default=0)
    is_active = models.BooleanField(default=True)

    def __str__(self):
        return '%s #%d' % (self.game, self.id)


class GamePrize(models.Model):
    """
    Stores default scoring for a particular ranking in a game session
    """
    game = models.ForeignKey('Game', on_delete=models.CASCADE)
    rank = models.IntegerField(default=1)
    score = models.IntegerField(default=0)

    def __str__(self):
        return '%d' % (self.rank)

    class Meta:
        unique_together = ("game", "rank")
        ordering = ['rank']


class Score(models.Model):
    """
    Base Model for Scoring
    """
    game_session = models.ForeignKey('GameSession', blank=True, null=True, on_delete=models.CASCADE)
    player = models.ForeignKey('players.Player', blank=True, null=True, on_delete=models.CASCADE)
    score = models.IntegerField(default=0, null=True, blank=True)

    def __str__(self):
        return "%d point(s)" % (self.score)


class SingleScore(Score):
    """
    Classic scoring system: you get what you are given
    """
    position = models.PositiveIntegerField(default=0)

    def save(self, *args, **kwargs):
        """
        Checks for null-score and if there is, update it with the score from GamePrize.

        :param args:
        :param kwargs:
        :return:
        """
        if self.score is None:
            try:
                prize = GamePrize.objects.get(rank=self.position, game=self.game_session.game)
                self.score = prize.score
            except GamePrize.DoesNotExist:
                self.score = self.game_session.game.base_score
            except MultipleObjectsReturned:
                self.score = 0

        super(SingleScore, self).save(*args, **kwargs)

    class Meta:
        ordering = ['position']


class AggregatedScore(Score):
    """
    Scoring system that is percentage based
    """

    def game(self):
        return self.game_session.game

    def average_score(self):
        cumulative_score = self.score
        judges_count = self.partialscore_set.count()
        if judges_count == 0:
            return 0
        return cumulative_score / judges_count


class PointCode(Score):
    """
    A 'scoring' system based on special predefined voucher-like codes
    """
    code = models.CharField(max_length=255)
    consumed_on = models.DateField(null=True, blank=True)

    def is_consumed(self):
        return self.consumed_on is not None

    def consume_code(self, player):
        self.player = player
        self.consumed_on = datetime.datetime.now()
        self.save()

    def __str__(self):
        return '%s' % (self.code)


# Score for an aggregated GameSession
class PartialScore(models.Model):
    """
    A score from a game master that contributes to the AggregatedScore
    """
    aggregated_score = models.ForeignKey('AggregatedScore', on_delete=models.CASCADE)
    percentage = models.PositiveSmallIntegerField(default=0)
    game_master = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    score = models.IntegerField(default=0)

    def __str__(self):
        return '%s' % (self.aggregated_score)

    class Meta:
        ordering = ['-percentage']
        unique_together = ("aggregated_score", "game_master")

scoreboard/forms.py
from django.forms import ModelForm
from .models import Score, PointCode
from games.models import Guess

# Form for scoreboard
class ScoreForm(ModelForm):
    class Meta:
        model = Score
        fields = ['score']

# Form for players who are guessing for a session
class GuessingForm(ModelForm):
    class Meta:
        model = Guess
        fields = ['guess']

# Form for redeeming PointCode
class PointCodeForm(ModelForm):
    class Meta:
        model = PointCode
        fields = ['code']

scoreboard/views.py
from django.contrib import messages
from django.contrib.admin.views.decorators import staff_member_required
from django.contrib.auth.decorators import login_required, permission_required
from django.db.models import F, Sum
from django.http import HttpResponseForbidden
from django.shortcuts import render, redirect, get_object_or_404
from django.utils.http import is_safe_url

from players.models import Player
from games.models import Guess

from .models import Game, Score, GameSession, PointCode
from .forms import GuessingForm, PointCodeForm


@staff_member_required
def scoreboard_view(request):

    overall_scores = Score.objects.exclude(player_id=None).annotate(player_id=F('player'),
                                                                    first_name=F('player__user__first_name'),
                                                                    last_name=F('player__user__last_name'))\
                                                          .values('player_id', 'first_name', 'last_name')\
                                                          .annotate(score=Sum('score'))\
                                                          .order_by('-score')

    games_list = []
    include_games = request.GET.get('includeindividual', False)

    if include_games:
        games = Game.objects.all()
        games_list = games.values('pk', 'name')

        for game in games_list:
            filtered_game_sessions = GameSession.objects.all().filter(game__pk=game['pk'])
            score_list = filtered_game_sessions.annotate(player_id=F('score__player'),
                                                         first_name=F('score__player__user__first_name'),
                                                         last_name=F('score__player__user__last_name'))\
                                               .values('player_id', 'first_name', 'last_name')\
                                               .annotate(score=Sum('score__score'))\
                                               .order_by('-score')
            game['score_list'] = score_list

    if request.GET.get('partial', False):
        return render(request, 'scoreboard/scoreboard_partial.html', {'overall': overall_scores})

    return render(request, 'scoreboard/scoreboard.html', {'games': games_list, 'overall': overall_scores,
                                                          'individualgames': include_games})


@login_required
def redemption_view(request):
    try:
        current_user_player = request.user.player
    except Player.DoesNotExist:
        current_user_player = None

    if not current_user_player:
        messages.error(request, 'Your are not a registered Player!')
        return redirect('/gfp-system')

    if request.method == 'POST':
        form = PointCodeForm(request.POST)
        if form.is_valid():
            point_code = PointCode.objects.filter(code=form.cleaned_data['code'], consumed_on=None)
            if point_code.exists():
                code = point_code[0]
                code.consume_code(current_user_player)
                messages.info(request, 'You have gained {points} points!'.format(points=code.score))
            else:
                messages.error(request, 'Invalid code provided!')
        else:
            messages.error(request, 'Invalid code provided!')

        redirect_url = request.POST.get('next', None)
        if redirect_url and is_safe_url(redirect_url):
            return redirect(redirect_url)
    else:
        form = PointCodeForm()

    return render(request, 'scoreboard/pointcode.html', {'form': form})


@login_required
def guess_view(request, id):
    associated_game_session = get_object_or_404(GameSession, pk=id)
    form = GuessingForm()
    if associated_game_session.game.game_type != Game.GUESSING:
        return HttpResponseForbidden()

    game_name = associated_game_session.game.name
    if request.method == 'POST':
        try:
            current_user_player = request.user.player
        except Player.DoesNotExist:
            current_user_player = None
        if current_user_player:
            guess_object, created = Guess.objects.get_or_create(player=current_user_player,
                                                                game_session=associated_game_session)
            form = GuessingForm(request.POST, instance=guess_object)
            if form.is_valid():
                new_guess = form.save()
                messages.info(request, 'Your guess has been successfully recorded!')
            else:
                messages.error(request, 'Something went wrong!')

            redirect_url = request.POST.get('next', None)
            if redirect_url and is_safe_url(redirect_url):
                return redirect(redirect_url)
        else:
            messages.warning(request, 'You are most likely a cheeky admin!')
    return render(request, 'scoreboard/guesser.html', {'form': form, 'game': game_name})

scoreboard/templates/scoreboard/guesser.html
{% extends "index.html" %}
{% load addcss %}

{% block body %}
<div class="jumbotron">
  <h2>{{ game }}</h2>
  <form method="POST" action="">
    {% csrf_token %}
   <div class="form-group">
     {{ form.guess | addcss:"form-control input-lg"}}
   </div>
   <button type="submit" class="btn btn-default">Submit</button>
  </form>
</div>
{% endblock %}

scoreboard/templates/scoreboard/pointcode.html
{% extends "index.html" %}
{% load addcss %}

{% block body %}
<div class="jumbotron">
  <h2>Enter your points code!</h2>
  <form method="POST" action="">
    {% csrf_token %}
   <div class="form-group">
     {{ form.code | addcss:"form-control input-lg"}}
   </div>
   <button type="submit" class="btn btn-default">Submit</button>
  </form>
</div>
{% endblock %}

scoreboard/templates/scoreboard/scoreboard.html
{% extends "index.html" %}

{% block extrajs_before %}
<script src="https://ajax.googleapis.com/ajax/libs/angularjs/1.5.7/angular.min.js"></script>
<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/angular-sanitize/1.5.7/angular-sanitize.min.js"></script>
<script>
var myScoreboardApp = angular.module('scoreboardApp', ['ngSanitize'])

myScoreboardApp.controller('ScoreboardController', ['$scope', '$http', '$timeout', function($scope, $http, $timeout) {
  $scope.reload = function () {
    $http.get('{% url 'scoreboard:scoreboard' %}?partial=1').
        success(function (data) {
          $scope.scoreboard = data;
      });

    $timeout(function(){
      $scope.reload();
    },30000)
  };
  $scope.reload();
}]);

angular.element(document).ready(function() {
  angular.bootstrap(document, ['scoreboardApp']);
});
</script>
{% endblock %}

{% block body %}
{% if not individualgames %}
<div ng-controller="ScoreboardController" ng-bind-html="scoreboard">
</div>
{% else %}
<ul class="nav nav-tabs" role="tablist">
    <li role="presentation"><a href="#tab-overall" aria-controls="tab-overall" role="tab" data-toggle="tab">Overall</a></li>
{% for value in games %}
	<li role="presentation"><a href="#tab-{{ value.pk }}" aria-controls="tab-{{ value.pk }}" role="tab" data-toggle="tab">{{ value.name }}</a></li>
{% endfor %}
</ul>
<div class="tab-content">
	<div role="tabpanel" class="tab-pane" id="tab-overall">
	<table class="table table-bordered">
		<thead>
			<th>NAME</th>
			<th>SCORE</th>
		</thead>
		{% for score in overall %}
		<tr>
	        <td>{{ score.first_name }} {{ score.last_name }}</td>
			<td>{{ score.score }}</td>
		</tr>
		{% endfor %}
	</table>
	</div>
	{% for game in games %}
	<div role="tabpanel" class="tab-pane" id="tab-{{ game.pk }}">
	<table class="table table-bordered">
		<thead>
			<td>NAME</td>
			<td>SCORE</td>
		</thead>
		{% for score in game.score_list %}
            {% if score.score %}
                <tr>
                    <td>{{ score.first_name }} {{ score.last_name }}</td>
                    <td>{{ score.score }}</td>
                </tr>
            {% endif %}
		{% endfor %}
	</table>
	</div>
	{% endfor %}
</div>
{% endif %}
{% endblock %}

scoreboard/templates/scoreboard/scoreboard_partial.html
<div class="row">
    <div class="col-xs-4">
        <div class="well text-center">
            <h2>1st</h2>
            <h4>{{ overall.0.first_name }} {{ overall.0.last_name }}</h4>
            <h3>{{ overall.0.score }}</h3>
        </div>
    </div>
    <div class="col-xs-4">
        <div class="well text-center">
            <h2>2nd</h2>
            <h4>{{ overall.1.first_name }} {{ overall.1.last_name }}</h4>
            <h3>{{ overall.1.score }}</h3>
        </div>
    </div>
    <div class="col-xs-4">
        <div class="well text-center">
            <h2>3rd</h2>
            <h4>{{ overall.2.first_name }} {{ overall.2.last_name }}</h4>
            <h3>{{ overall.2.score }}</h3>
        </div>
    </div>
</div>

<div class="row">
    <div class="col-xs-12">
        <table class="table table-bordered">
		<thead>
			<th>NAME</th>
			<th>SCORE</th>
		</thead>
		{% for score in overall|slice:"3:" %}
            <tr>
                <td>{{ score.first_name }} {{ score.last_name }}</td>
                <td>{{ score.score }}</td>
            </tr>
		{% endfor %}
	</table>
    </div>
</div>

scoreboard/templates/scoreboard/update.html
{% extends "index.html" %}