gfp/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^$', 'players.views.index', name='players-index'),
    url(r'^gfp-system/', include('scoreboard.urls', namespace='scoreboard')),
    url(r'^player/', include('players.urls', namespace='players')),
    url(r'^games/', include('games.urls', namespace='games')),
    url(r'^grappelli/', include('grappelli.urls')),
    url(r'^admin/', admin.site.urls)
]

players/urls.py
from django.conf.urls import url
from django.contrib.auth import views as auth_views


from . import views

urlpatterns = [
    url(r'^login$', views.login_view, name="players-login"),
    url(r'^logout$', auth_views.logout, name="players-logout")
]

gfp/templates/index.html
<!doctype html>
<html class="no-js" lang="">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
        <title>NUS SoC GFP</title>
        <meta name="description" content="">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="apple-touch-icon" href="apple-touch-icon.png">

        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" integrity="sha384-1q8mTJOASx8j1Au+a5WDVnPi2lkFfwwEAa8hDDdjZlpLegxhjVME1fgjWPGmkzs7" crossorigin="anonymous">
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/normalize/3.0.2/normalize.min.css" integrity="sha384-NJuY0uR1degN4HwNbGPc5TnCwafsDNYBP52/Hp3GuqSjU2tpMk1fw/NrkzvOfPfz" crossorigin="anonymous">
        <link rel="stylesheet" href="css/main.css">

        <script src="js/vendor/modernizr-2.8.3.min.js"></script>
        {% block extrajs_before %}
        {% endblock %}
    </head>
    <body>
        <!--[if lt IE 8]>
            <p class="browserupgrade">You are using an <strong>outdated</strong> browser. Please <a href="http://browsehappy.com/">upgrade your browser</a> to improve your experience.</p>
        <![endif]-->
        <div class="container">
          <nav class="navbar navbar-default">
            <div class="container-fluid">
              <!-- Brand and toggle get grouped for better mobile display -->
              <div class="navbar-header">
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
                  <span class="sr-only">Toggle navigation</span>
                  <span class="icon-bar"></span>
                  <span class="icon-bar"></span>
                  <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="#">NUS GFP System</a>
              </div>

              <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav">
                </ul>
                <ul class="nav navbar-nav navbar-right">
                  {% if user.is_authenticated %}
                      <li class="dropdown">
                          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
                              Signed in as {{ user.username }}&nbsp;<span class="caret"></span></a>
                          <ul class="dropdown-menu">
                            <li><a href="{% url 'players:players-logout' %}?next={% url 'players-index' %}">Logout</a></li>
                          </ul>
                      </li>
                  {% else %}
                    <li><a href="{% url 'players:players-login' %}">Login</a></li>
                  {% endif %}
                </ul>
              </div><!-- /.navbar-collapse -->
            </div><!-- /.container-fluid -->
          </nav>
          {% if messages %}
            {% for message in messages %}
            <div class="alert alert-{{ message.level_tag }} alert-dismissible" role="alert">
              <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
              {{ message }}
            </div>
            {% endfor %}
          {% endif %}

          {% if form.non_field_errors %}
            {% for error in form.non_field_errors %}
              <div class="alert alert-danger alert-dismissible" role="alert">
                <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                {{ error|escape }}
              </div>
            {% endfor %}
          {% endif %}
          {% block body %}

          {% endblock %}
        </div>

        <script src="//ajax.googleapis.com/ajax/libs/jquery/1.11.2/jquery.min.js"></script>
        <script>window.jQuery || document.write('<script src="js/vendor/jquery-1.11.2.min.js"><\/script>')</script>

        <!-- Latest compiled and minified JavaScript -->
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js" integrity="sha384-0mSbJDEHialfmuBBQP6A4Qrprq5OVfW37PRR3j5ELqxss1yVqOtnepnHVP9aJ7xS" crossorigin="anonymous"></script>
        <script src="js/plugins.js"></script>
        <script src="js/main.js"></script>
        {% block extrajs %}

        {% endblock %}
    </body>
</html>